name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android 34 platforms & build-tools
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0"

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Set up Gradle (no cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-disabled: true

      - name: Build debug APK (verbose)
        run: |
          gradle --version
          gradle --no-daemon assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
